
#1. List the number of films per category.
select film_category.category_id, count(*) AS total
from film_category
inner join category on film_category.category_id = category.category_id
group by category.category_id;


#2. Retrieve the store ID, city, and country for each store.


    select store.store_id, address.address, country
    from store
    inner join address on store.address_id = address.address_id
	inner join city on address.city_id = city.city_id
    inner join country on country.country_id = city.country_id;
    
    
#3.  Calculate the total revenue generated by each store in dollars.
select *
SELECT store, total_sales FROM sakila.sales_by_store;
​
#4.  Determine the average running time of films for each category.
SELECT category_id, AVG(length)
FROM sakila.film_category
INNER JOIN sakila.film
ON sakila.film_category.film_id = sakila.film.film_id
